### ISSUE TITLE
"An error occurred while signing into Mendeley"

### ISSUE THREAD

**Issue by dougkoellmer** [Mendeley/mendeley-android-sdk#52]
Our Android app is now getting this message in a toast whenever a user tries to sign in. Our iOS and Web properties are still working fine. I've been trying to debug this myself for about a day and I have some leads and am starting to understand the code a bit better. I wanted to have more information and suggestions to give but I figured now is a good point to ask if there's something obvious I can try to get this fixed. Our app has been using this Mendeley SDK flawlessly for years and this just cropped up. I figure something must have changed on your servers.

Here are relevant logs:

```
06-02 17:23:23.242 30175 30279 W DefaultRequestDirector: Authentication error: Unable to respond to any of these challenges: {bearer=WWW-Authenticate: Bearer realm="mendeley" error="invalid_token"}
06-02 17:23:23.243 30175 30279 E SharedPreferencesCredentialsManager: Error token string: {"message":"Could not access resource because: No auth header","errorId":"oauth/NOT_AUTHORIZED"}
06-02 17:23:23.245 30175 30279 E DialogActivity: 
06-02 17:23:23.245 30175 30279 E DialogActivity: org.json.JSONException: No value for access_token
06-02 17:23:23.245 30175 30279 E DialogActivity: 	at org.json.JSONObject.get(JSONObject.java:389)
06-02 17:23:23.245 30175 30279 E DialogActivity: 	at org.json.JSONObject.getString(JSONObject.java:550)
06-02 17:23:23.245 30175 30279 E DialogActivity: 	at com.mendeley.api.auth.SharedPreferencesCredentialsManager.setCredentials(SharedPreferencesCredentialsManager.java:43)
06-02 17:23:23.245 30175 30279 E DialogActivity: 	at com.mendeley.api.auth.AuthenticationManager.setTokenDetails(AuthenticationManager.java:134)
06-02 17:23:23.245 30175 30279 E DialogActivity: 	at com.mendeley.api.activity.DialogActivity$AuthenticateTask.doInBackground(DialogActivity.java:186)
06-02 17:23:23.245 30175 30279 E DialogActivity: 	at com.mendeley.api.activity.DialogActivity$AuthenticateTask.doInBackground(DialogActivity.java:158)
06-02 17:23:23.245 30175 30279 E DialogActivity: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
06-02 17:23:23.245 30175 30279 E DialogActivity: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-02 17:23:23.245 30175 30279 E DialogActivity: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
06-02 17:23:23.245 30175 30279 E DialogActivity: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-02 17:23:23.245 30175 30279 E DialogActivity: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-02 17:23:23.245 30175 30279 E DialogActivity: 	at java.lang.Thread.run(Thread.java:818)
```

Thank you for the great library and for any help you can provide!

**Comment by A-BEECHEY** [comment]
@dougkoellmer, 
thanks for getting in touch and your positive feedback on our library.
Im sorry to hear you are having issues.
Is there any chance you could supply a complete HTTP request that includes all the headers and body for one of these failures?

**Comment by dougkoellmer** [comment]
Thanks for your response. I got sidetracked but will try to get you that information.

**Comment by dougkoellmer** [comment]
It turns out I just had to upgrade to the latest version of the library. Sorry for the trouble!

**Comment by A-BEECHEY** [comment]
@dougkoellmer Im glad to hear you have resolved your issue.
